FinalProject/Controllers/FriendsController.cs
using BLL.DTO;
using BLL.Interfaces;
using FinalProject.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace FinalProject.Controllers
{
    /// <summary>
    /// Friends controller.
    /// </summary>
    /// <remarks>
    /// Evailable only for user with role User.
    /// </remarks>
    [Authorize(Roles = "User")]
    public class FriendsController : Controller
    {
        IContactService contactService;

        /// <summary>
        /// Public constructor set contact service.
        /// </summary>
        /// <param name="service">Contact service.</param>
        public FriendsController(IContactService service)
        {
            contactService = service;
        }

        /// <summary>
        /// Get user service from HttpContext.
        /// </summary>
        private IUserService UserService
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<IUserService>();
            }
        }

        /// <summary>
        /// Returns id of current autorized user.
        /// </summary>
        private string CurrentUserId
        {
            get
            {
                return User.Identity.GetUserId();
            }
        }

        /// <summary>
        /// Http get action show user fliends.
        /// </summary>
        /// <returns>View with user friends.</returns>
        [HttpGet]
        public async Task<ActionResult> GetUserFriends()
        {
            UserDTO currentUserDTO = await UserService.GetUserById(CurrentUserId);
            if (currentUserDTO == null)
                return RedirectToAction("SingOut", "Home");

            FriendsViewModel friendsViewModel = new FriendsViewModel();
            currentUserDTO.UserId = User.Identity.GetUserId();
            friendsViewModel.UserName = currentUserDTO.Name;

            friendsViewModel.userProfileViewModel = new UserProfileViewModel
            {
                UserName = currentUserDTO.Name,
                Birthday = currentUserDTO.Birthday,
                Status = currentUserDTO.Status,
                Email = currentUserDTO.Email,
                UserId = currentUserDTO.UserId,
                PhoneNumber = currentUserDTO.PhoneNumber
            };

            friendsViewModel.Contacts = await contactService.GetContactsByUserIdAsync(currentUserDTO.UserId);

            return View(friendsViewModel);
        }

        /// <summary>
        /// Http post action add friend by user id.
        /// </summary>
        /// <param name="UserId">Friend id to add.</param>
        /// <returns>Redirect to action GetUserFriends.</returns>
        [HttpPost]
        public async Task<ActionResult> AddFriend(string UserId)
        {
            await contactService.AddContactAsync(new ContactDTO {
                UserId = CurrentUserId,
                ContactUserId = UserId
            });

            return RedirectToAction("GetUserFriends");
        }

        /// <summary>
        /// Find users by entered searching terms.
        /// </summary>
        /// <param name="friendsSearchViewModel">View model with terms to search.</param>
        /// <returns>Partial view FriendsSearchPartial.</returns>
        [HttpGet]
        public async Task<ActionResult> FindUsers(FriendsSearchViewModel friendsSearchViewModel)
        {
            friendsSearchViewModel.SearchedUsers = await UserService.FindUsers(new UserDTO
            {
                Name = friendsSearchViewModel.NameToSearch,
                Email = friendsSearchViewModel.MailToSearch,
                PhoneNumber = friendsSearchViewModel.PhoneToSearch,
                UserId = CurrentUserId
            });

            return PartialView("FriendsSearchPartial", friendsSearchViewModel);
        }

        /// <summary>
        /// Http post action delete friend by contact id.
        /// </summary>
        /// <param name="ContactId">Contact id to delete.</param>
        /// <returns>Redirect to action GetUserFriends.</returns>
        [HttpPost]
        public async Task<ActionResult> DeleteFriend(int ContactId)
        {
            await contactService.DeleteContactAsync(ContactId);
            return RedirectToAction("GetUserFriends");
        }

        /// <summary>
        /// Disposes services.
        /// </summary>
        protected override void Dispose(bool disposing)
        {
            UserService.Dispose();
            contactService.Dispose();
            base.Dispose(disposing);
        }
    }
}

FinalProject/Controllers/HomeController.cs
using BLL.DTO;
using BLL.Interfaces;
using FinalProject.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace FinalProject.Controllers
{
    /// <summary>
    /// Home contoller.
    /// </summary>
    /// <remarks>
    /// Evailable only for users with role User.
    /// </remarks>
    [Authorize(Roles = "User")]
    public class HomeController : Controller
    {
        IChatService chatService;

        /// <summary>
        /// Public constructor set chat service.
        /// </summary>
        /// <param name="service">Chat service.</param>
        public HomeController(IChatService service)
        {
            chatService = service;
        }

        /// <summary>
        /// Get user service from HttpContext.
        /// </summary>
        private IUserService UserService
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<IUserService>();
            }
        }

        /// <summary>
        /// Returns id of current autorized user.
        /// </summary>
        private string CurrentUserId
        {
            get
            {
                return User.Identity.GetUserId();
            }
        }

        /// <summary>
        /// Shows main page with user chats.
        /// </summary>
        /// <returns>Index view with chats and current user profile information.</returns>
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            UserDTO currentUserDTO = await UserService.GetUserById(CurrentUserId);
            if (currentUserDTO == null)
                await SingOut();

            currentUserDTO.UserId = CurrentUserId;
            IndexViewModel indexViewModel = new IndexViewModel();
            indexViewModel.UserName = currentUserDTO.Name;
            IEnumerable<ChatDTO> chats = await chatService.GetChatsAsync(currentUserDTO.UserId);
            indexViewModel.Chats = chats;

            indexViewModel.userProfileViewModel = new UserProfileViewModel
            {
                UserName = currentUserDTO.Name,
                Birthday = currentUserDTO.Birthday,
                Status = currentUserDTO.Status,
                Email = currentUserDTO.Email,
                UserId = currentUserDTO.UserId,
                PhoneNumber = currentUserDTO.PhoneNumber
            };

            return View(indexViewModel);
        }

        /// <summary>
        /// Shows partial view with chat messages.
        /// </summary>
        /// <param name="ChatId">Chat id to get messages.</param>
        /// <returns>Partial view ChatMessages with messages.</returns>
        [HttpGet]
        public async Task<ActionResult> ChatMessages(int ChatId)
        {
            if (Request.IsAjaxRequest() == false)
                return RedirectToAction("Index");

            ChatDTO currentChatDTO = await chatService.GetChat(new ChatDTO { 
                ChatId = ChatId, 
                ConcreteUserId = CurrentUserId
            });

            ChatViewModel chatViewModel = new ChatViewModel {
                ChatMessages = await chatService.GetMessagesByChatIdAsync(ChatId),
                ChatId = ChatId,
                CurrentUserId = CurrentUserId,
                FriendName = currentChatDTO.ContactName
            };

            return PartialView(chatViewModel);
        }

        /// <summary>
        /// Shows evailable chats to adding.
        /// </summary>
        /// <param name="indexViewModel">indexViewModel.</param>
        /// <returns>Partial view ChatsAddingPartial.</returns>
        [HttpGet]
        public async Task<ActionResult> AvailableChats(IndexViewModel indexViewModel)
        {
            indexViewModel.Chats = await chatService.GetAvailableForAddingChatsAsync(CurrentUserId);
            return PartialView("ChatsAddingPartial", indexViewModel);
        }

        /// <summary>
        /// Post action refuse chat deleting.
        /// </summary>
        /// <param name="ChatId">Chat id to refuse.</param>
        /// <returns>Redirect to index action.</returns>
        [HttpPost]
        public async Task<ActionResult> ReestablishChat(int ChatId)
        {
            await chatService.ReestablishChat(ChatId);
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Post action delete chat by id.
        /// </summary>
        /// <param name="ChatId">Chat id to delete.</param>
        /// <returns>Redirect to index action.</returns>
        [HttpPost]
        public async Task<ActionResult> DeleteChat(int ChatId)
        {
            await chatService.DeleteChatById(ChatId);
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Post action send message to chat.
        /// </summary>
        /// <param name="chatViewModel">Chat view model with new message text and chat id.</param>
        /// <returns>Partial view ChatMessages.</returns>
        [HttpPost]
        public async Task<ActionResult> SendMessage(ChatViewModel chatViewModel)
        {
            ChatDTO currentChatDTO = await chatService.GetChat(new ChatDTO
            {
                ChatId = chatViewModel.ChatId,
                ConcreteUserId = CurrentUserId
            });

            if (ModelState.IsValid)
            {
                await chatService.SendMessageToChat(new MessageDTO
                {
                    ChatId = chatViewModel.ChatId,
                    Text = chatViewModel.NewMessageText,
                    Date = DateTime.Now.ToString(),
                    MassageSenderId = CurrentUserId,
                });

                chatViewModel.ChatMessages = await chatService.GetMessagesByChatIdAsync(chatViewModel.ChatId);
                chatViewModel.CurrentUserId = CurrentUserId;
                chatViewModel.FriendName = currentChatDTO.ContactName;
                return PartialView("ChatMessages", chatViewModel);
            }
            else
            {
                chatViewModel.ChatMessages = await chatService.GetMessagesByChatIdAsync(chatViewModel.ChatId);
                chatViewModel.CurrentUserId = CurrentUserId;
                chatViewModel.FriendName = currentChatDTO.ContactName;
                return PartialView("ChatMessages", chatViewModel);
            }
        }

        /// <summary>
        /// Post action send edit user profile information.
        /// </summary>
        /// <param name="userProfileViewModel">User profile view model with entered new user profile data.</param>
        /// <returns>Partial view UserProfilePartial.</returns>
        [HttpPost]
        public async Task<ActionResult> EditUserProfile(UserProfileViewModel userProfileViewModel)
        {
            if(ModelState.IsValid)
            {
                await UserService.UpdateUserProfile(new UserDTO
                {
                    UserId = CurrentUserId,
                    Birthday = userProfileViewModel.Birthday,
                    Status = userProfileViewModel.Status,
                    Name = userProfileViewModel.UserName,
                    PhoneNumber = userProfileViewModel.PhoneNumber,
                });
                userProfileViewModel.IsUpdateSuccess = true;
            }
           
            return PartialView("UserProfilePartial", userProfileViewModel);
        }

        /// <summary>
        /// Post action send message complaint.
        /// </summary>
        /// <param name="complaint">Message complaint view model with entered complaint text and message id.</param>
        /// <returns>Partial view MessageComplaintInputPartial.</returns>
        [HttpPost] 
        public async Task<ActionResult> SendMessageCompalint(MessageComplaintViewModel complaint)
        {
            if (ModelState.IsValid) 
            {
                await chatService.CreateMessageComplaint(new MessageComplaintDTO {
                    MessageId = complaint.MessageId,
                    ComplaintText  = complaint.ComplaintText,
                    AccuserUserId = CurrentUserId
                });

                complaint.IsUpdateSuccess = true;
                return PartialView("MessageComplaintInputPartial", complaint);
            }
            return PartialView("MessageComplaintInputPartial", complaint);
        }

        /// <summary>
        /// Sing out.
        /// </summary>
        /// <remarks>
        /// Evailable for any users from any parts of program.
        /// </remarks>
        /// <returns>Redirec to Account/Login action.</returns>
        [AllowAnonymous]
        [HttpGet]
        public async Task<ActionResult> SingOut()
        {
            var AuthenticationManager = HttpContext.GetOwinContext().Authentication;
            await Task.Run(() => AuthenticationManager.SignOut()); 
            return RedirectToAction("Login", "Account");
        }

        /// <summary>
        /// Disposes services.
        /// </summary>
        protected override void Dispose(bool disposing)
        {
            chatService.Dispose();
            UserService.Dispose();
            base.Dispose(disposing);
        }
    }
}

FinalProject/Views/Home/ChatMessages.cshtml
@model FinalProject.Models.ChatViewModel
@using FinalProject.Models;

<div class="horizontalContainer" id="chatBar">
    <img alt="picture" src="/Content/Images/user.png" class="userIcon">
    <p class="labelTextWhight">@Model.FriendName</p>
    <img alt="picture" src="/Content/Images/trash.png" class="userIcon" id="trashIcon" onclick="DeleteClickHendler(chatBar)">
    @using (Html.BeginForm("DeleteChat", "Home", new { ChatId = Model.ChatId }, FormMethod.Post))
    {
        <input class="submitBtn" id="deleteChat" type="submit" style="display:none;" onclick="return confirm('Delete chat with @Model.FriendName?')" />
    }
</div>
<div id="ChatMessagesContainer">
    @foreach (var massage in Model.ChatMessages)
    {
        if (massage.MassageSenderId == Model.CurrentUserId)
        {
            <div class="list-group-item list-group-item-action flex-column align-items-start message messageRight">
                <div class="d-flex w-100 justify-content-between">
                    <small>@massage.Date</small>
                </div>
                <p class="mb-1">@massage.Text</p>
            </div>
        }
        else
        {
            <div class="horizontalContainer" id="friendMessage">
                <img alt="picture" src="/Content/Images/user_blck.png" class="userIcon">
                <div class="list-group-item list-group-item-action flex-column align-items-start message messageLeft">
                    <div class="d-flex w-100 justify-content-between">
                        <small style="margin-bottom: 5px;">
                            @massage.Date
                            <img alt="picture" src="/Content/Images/complaint.png" class="complaintIcon" onclick="OpenMessageComplaint(this)">
                        </small>
                    </div>
                    <p class="mb-1">@massage.Text</p>
                </div>

                <div id="showMessageComplaint" class="modal fade" tabindex="-1" role="dialog">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content" style=" background-color: rgb(102,193,163);">
                            <div class="modal-header">
                                <h4 class="modal-title">Message complaint</h4>
                                <button type="button" id="closeMessageComplaint" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            </div>
                            @{
                                Html.RenderPartial("MessageComplaintInputPartial", new MessageComplaintViewModel {  MessageId = massage.MessageId });
                            }
                        </div>
                    </div>
                </div>
                <button id='openMessageComplaint' data-toggle="modal" data-target="#showMessageComplaint" style="display:none;">open modal</button>
            </div>
        }
    }
</div>
<div class="horizontalContainer" id="chatMessageInputBar">
    @Html.Partial("MessageInputPartial")
</div>

FinalProject/Views/Home/ChatsAddingPartial.cshtml
@model FinalProject.Models.IndexViewModel

<div class="verticalContainer" id="chatsSearching" style="margin-top:5%;margin-bottom:5%;">
    @using (Ajax.BeginForm("AvailableChats", "Home", "", new AjaxOptions { UpdateTargetId = "chatsSearching", HttpMethod = "Get" }, new { @class = "verticalContainer" }))
    {
        <input class="submitBtn" id="showEvailableChats" type="submit" value="Find chats" style="display:none;" />
    }
<div class="verticalContainer" id="searchedChats" style="margin-top:10%;">
    @if (Model.Chats.Count() == 0)
    {
        <p class="labelTextWhight">There aren't any chats to add.</p>
    }
    @foreach (var chat in Model.Chats)
    {
        <div class="horizontalContainer" id="friendContainer">
            <img alt="picture" src="/Content/Images/user.png" class="userIcon">
            <div class="list-group-item list-group-item-action flex-column align-items-start" id="friendBoxSearch">
                <div class="d-flex w-100 justify-content-between">
                    <small>
                        <span class="plusGreen" onclick="DeleteClickHendler(this)">
                            @using (Html.BeginForm("ReestablishChat", "Home", new { ChatId = chat.ChatId }, FormMethod.Post))
                            {
                                <input class="submitBtn" type="submit" style="display:none;" onclick="return confirm('Reestablish chat with @chat.ContactName?')" />
                            }
                        </span>
                    </small>
                </div>
                <p class="mb-2">@chat.ContactName</p>
            </div>
        </div>
    }
</div>
</div>

FinalProject/Views/Home/Index.cshtml
@model FinalProject.Models.IndexViewModel
@using FinalProject.App_Code;
@using FinalProject.Models;
@using BLL.DTO

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    #sticky-footer {
        display:none;
    }
</style>
<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" id="navBar">
        <a class="navbar-brand" href="#">Simple Social Network</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("Index","Home")">Chats <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("GetUserFriends","Friends")">Friends</a>
                </li>
            </ul>
            <form class="form-inline mt-2 mt-md-0">
                @Html.ShowUserOptions(Model.UserName)
            </form>
        </div>
    </nav>
</header>
<div class="content">
    <div class="fullScreenFlexContainer">
        <div class="verticalContainer" id="chatsContainer">
            @foreach (var item in Model.Chats)
            {
                <div class="horizontalContainerUserImageAndChat">
                    <img alt="picture" src="/Content/Images/user_blck.png" class="userIcon">
                    <div class="list-group-item list-group-item-action flex-column align-items-start" id="chatBox" onclick="OpenChat()">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">@item.ContactName</h5>
                            <small>@item.LastMassageDate</small>
                        </div>
                        <p class="mb-1">@item.LastMassageText</p>
                        @Ajax.ActionLink(" ", "ChatMessages", new { ChatId = @item.ChatId },
                        new AjaxOptions { UpdateTargetId = "ChatMessages", OnSuccess = "ScrollMessagesDown" }, new { id = "ActionLink" })
                    </div>
                </div>
            }
            <button class="plusBtn" type="button" onclick="return OpenChatsAdding()">
                <span class="plus"></span>
            </button>

            <div id="showmodal" class="modal fade" tabindex="-1" role="dialog">
                <div class="modal-dialog" role="document">
                    <div class="modal-content" style=" background-color: rgb(102,193,163);">
                        <div class="modal-header">
                            <h4 class="modal-title">Profile</h4>
                            <button type="button" id="userProfileCloseBtn" class="close" data-dismiss="modal" aria-label="Close" onclick="RefreshMain()"><span aria-hidden="true">&times;</span></button>
                        </div>
                        @{
                            Html.RenderPartial("UserProfilePartial", Model.userProfileViewModel);
                        }
                    </div>
                </div>
            </div>
            <button id='open' data-toggle="modal" data-target="#showmodal" style="display:none;">open modal</button>

            <div id="showChatsAdding" class="modal fade" tabindex="-1" role="dialog">
                <div class="modal-dialog" role="document">
                    <div class="modal-content" style=" background-color: rgb(102,193,163);">
                        <div class="modal-header">
                            <h4 class="modal-title">Chats Adding</h4>
                            <button type="button" id="closebtn" class="close" data-dismiss="modal" aria-label="Close" onclick="RefreshMain()"><span aria-hidden="true">&times;</span></button>
                        </div>
                        @{
                            Html.RenderPartial("ChatsAddingPartial", new IndexViewModel { userProfileViewModel = Model.userProfileViewModel, Chats = new List<ChatDTO>() });
                        }
                    </div>
                </div>
            </div>
            <button id='openChatsAdding' data-toggle="modal" data-target="#showChatsAdding" style="display:none;">open modal</button>

           

        </div>
        <div id="ChatMessages">
            <div class="horizontalContainer fullScreenFlexContainer">
                <p>Choose the chat!</p>
            </div>
        </div>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/scripts/jquery-1.10.2.min.js")
        @Scripts.Render("~/scripts/jquery.unobtrusive-ajax.min.js")
    </div>
</div>

FinalProject/Views/Home/MessageComplaintInputPartial.cshtml
@model FinalProject.Models.MessageComplaintViewModel
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script type="text/javascript">
    @if (Model.IsUpdateSuccess == true)
    {
        @:CloseMessageComplaint();
    }
</script>
<div class="verticalContainer" id="messageComplaintForm" style="margin-top:5%;margin-bottom:5%;">
    @using (Ajax.BeginForm("SendMessageCompalint", "Home", new AjaxOptions
    {
        UpdateTargetId = "messageComplaintForm",
        HttpMethod = "Post",
    }, new { @class = "verticalContainer" }))
    {
        @Html.ValidationSummary(true)
        @Html.LabelFor(model => model.ComplaintText, new { @class = "labelTextWhight" })
        @Html.EditorFor(model => model.ComplaintText)
        @Html.ValidationMessageFor(model => model.ComplaintText, "", new { @class = "text-danger" })

        @Html.HiddenFor(modelItem => Model.MessageId)
        <input class="submitBtn" id="deleteChat" type="submit" value="Send" />
    }
</div>

FinalProject/Views/Home/MessageInputPartial.cshtml
@model FinalProject.Models.ChatViewModel

<style>
    input.input-validation-error {
        border-color: red;
    }
</style>
@using (Ajax.BeginForm("SendMessage", "Home", new { ChatId = Model.ChatId}, new AjaxOptions {
    UpdateTargetId = "ChatMessages",
    HttpMethod = "Post",
    OnSuccess = "ScrollMessagesDown"
}, new { style = "width:100%" }))
{  

    @Html.EditorFor(model => model.NewMessageText, new { htmlAttributes = new { style = "width: 70%", @id="messageInput" } })
    <input class="submitBtn" id="btnSubmitMessage" type="submit" value="Send"/>
}

FinalProject/Views/Home/UserProfilePartial.cshtml
@model FinalProject.Models.UserProfileViewModel
@using FinalProject.App_Code;
@using FinalProject.Models;

@{
    ViewBag.Title = "UserProfile";
}

<script type="text/javascript">
    @if (Model.IsUpdateSuccess == true)
    {
        @:CloseUserProfile();
    }
</script>
<div class="verticalContainer" id="userProfileContent" style="margin-top:5%;margin-bottom:5%;">
    <img alt="UserIcon" src="/Content/Images/user.png" style="width:100px;height:100px;">
    @using (Ajax.BeginForm("EditUserProfile", "Home", "", new AjaxOptions { UpdateTargetId = "userProfileContent" }, new { @class = "verticalContainer" }))
    {
        @Html.LabelFor(model => model.UserName, new { @class = "labelTextGreen" })
        @Html.EditorFor(model => model.UserName, new { default_value = Model.UserName })
        @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })

        @Html.LabelFor(model => model.PhoneNumber, new { @class = "labelTextGreen" })
        @Html.EditorFor(model => model.PhoneNumber, new { default_value = Model.PhoneNumber });
        @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })

        @Html.LabelFor(model => model.Birthday, new { @class = "labelTextGreen" })
        @Html.EditorFor(model => model.Birthday, new { default_value = Model.Birthday });
        @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })

        @Html.LabelFor(model => model.Status, new { @class = "labelTextGreen" })
        @Html.EditorFor(model => model.Status, new { default_value = Model.Status });
        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })

        <input class="submitBtn" type="submit" value="Save" />

    }
</div>